services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      API_PORT: "3000"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - server
